### ISSUE TITLE
Change algorithm.yaml template code to add comment explaining every argument. 

### ISSUE THREAD

**Issue by sujen1412** [MAAP-Project/Community#252]
Currently it looks something like this 
```
# DO NOT DELETE
# THIS CONFIG IS AUTO-GENERATED BY ADE UI
algo_name: run_above
version: master
environment: ubuntu
repository_url: https://mas.maap-project.org/lauraiduncanson/atl08_extract_repo.git
docker_url: mas.maap-project.org:5000/root/ade_base_images/r:latest
# queue chosen when registering
memory: 15GB

# fill out these fields
# explain what this algorithm does
description: 
# path to the wrapper script for running the algorithm
run_command: /projects/above/gitlab_repos/atl08_extract_repo/run_above.sh
# set a storage value in GB or MB or KB, e.g. "100GB", "20MB", "10KB"
disk_space: 10GB
inputs:
# remove below this line if no inputs
# rename and set algorithm input names accordingly
  - name: icesat2_granule
    download: True

```

We should augment it to something like this 

```
# DO NOT DELETE
# THIS CONFIG IS AUTO-GENERATED BY ADE UI
algo_name: run_above
# Branch name of your repo
version: master
environment: ubuntu

# Repositories currently supported are the ones hosted on repo.nasa.maap.xyz and mas.maap-project.org 
repository_url: https://mas.maap-project.org/lauraiduncanson/atl08_extract_repo.git

# Make sure to replace the version var with an actual value like "latest"
docker_url: mas.maap-project.org:5000/root/ade_base_images/r:${version}
# queue chosen when registering
memory: 15GB

# fill out these fields
# explain what this algorithm does
description: 
# path to the wrapper script for running the algorithm. Note the path should be relative from the top level of your repo
# eg. <repo_name>/myscript.sh
run_command: /projects/above/gitlab_repos/atl08_extract_repo/run_above.sh
# set a storage value in GB or MB or KB, e.g. "100GB", "20MB", "10KB"
disk_space: 10GB
inputs:
# remove below this line if no inputs
# rename and set algorithm input names accordingly
  - name: icesat2_granule
    download: True
```
